name: Build and Test ParkingPatrolWebApp
on: workflow_dispatch
#on: push
jobs:
  build-project:
    name: Build and Test ParkingPatrolWebApp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: install node v18
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - name: Install Npm dependencies
        run: npm install
      #- name: Test application
      #  run: npm run test
      - name: Build application
        run: npm run build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to Docjer Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: pm4parkingpatrol/test:latest, pm4parkingpatrol/test:${{ github.run_number }}
