name: Continuous Deployment Kubernetes

on: workflow_dispatch

# on:
#  push:
#    branches: [ "main" ]
  
jobs:
  deploy:
    name: Deploy
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - name: redeploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBERNETES_CONFIG }}
          version: v1.21.0 # specify kubectl binary version explicitly
          binaries-url: "https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl" # specify the download url explicitly
          command: -n nightparkingpatrol-prod rollout status deployment/test-next-deployment
